### ISSUE TITLE
Virustotal

### ISSUE THREAD

**Issue by Verity-Freedom** [Verity-Freedom/Tor-Portable#1]
Антивирусы Вирустотала определяют AntiTor.exe как вирус в 22 из 66 случаев. Хочу сказать, что они все дают ложноположительный результат, и об этом лично мне хорошо известно. Если бы файл действительно был вирусом, его бы посчитали таковым как минимум в половине случаев.

**Comment by Sidiusz** [comment]
А если бы в половине, ты бы написал "хотя бы в 70% случаев"?

**Comment by Verity-Freedom** [comment]
> А если бы в половине, ты бы написал "хотя бы в 70% случаев"?

"Если бы у бабушки были мужские половые органы, она была бы дедушкой"

**Comment by Sidiusz** [comment]
Не стоит скачивать приложение
