### ISSUE TITLE
Несовместимость с Win 7

### ISSUE THREAD

**Issue by Verity-Freedom** [Verity-Freedom/Tor-Portable#13]
В данный момент Тор полностью совместим с Win 7. Но в новой версии судя по всему совместимость с ней в Тор убрали. Я подожду некоторое время и не буду обновлять Тор эксперт. Однако если ситуация сохранится, то и мне придётся принять её.

**Comment by 40OIL** [comment]
На сайте тора написано, что 13я версия продолжает обновляться и остается совместимой с вин7, а 14я и старше - только для вин10 и выше

**Comment by Verity-Freedom** [comment]
> На сайте тора написано, что 13я версия продолжает обновляться и остается совместимой с вин7, а 14я и старше - только для вин10 и выше

@40OIL будут две версии. Я тоже видел Тор Эксперт последний на основе 14-й версии. Я разделю в релизе версии для вин 10 и версию для вин 7.

**Comment by Verity-Freedom** [comment]
@40OIL создал небольшой багрепорт на сайте Тора.
https://forum.torproject.org/t/0-4-8-13-tor-expert-bundle-doesnt-work-on-win-7/15681

**Comment by Verity-Freedom** [comment]
@40OIL речь идёт как я понимаю о краше lyrebird (мосты), а не самого Тора. Сам Тор на вин 7 всё ещё работает. Я попробую достучаться до разработчиков и предоставить логи.

**Comment by Verity-Freedom** [comment]
@40OIL нам желательно также зарегистрироваться на гитлабе Тора (там всё сложно с этим и меня пока не пропустили), я полагаю у тебя тоже есть седьмая винда в доступности.
https://gitlab.torproject.org

**Comment by Verity-Freedom** [comment]
Мне в принципе подойдёт кто угодно с рабочим аккаунтом на гитлабе просто чтобы передать логи дебага.

**Comment by Verity-Freedom** [comment]
@40OIL поговорил с главными разрабами(!!!) Тора на матриксе, они теперь знают о проблеме. Сказали что lyrebird сделан на основе языка go, который больше не поддерживает win 7. Собственно предложили оставить lyrebird от предыдущей версии, а tor exe и tor gencert от следующих. Так и сделаю, теперь будут они это фиксить или не будут зависит от них, но скорее не будут чем будут, ибо у них нет ни одного компа с вин 7. Так что будет просто параллельно две версии.
