### ISSUE TITLE
Сбой Антизапрета 07.12.24

### ISSUE THREAD

**Issue by Verity-Freedom** [Verity-Freedom/Tor-Portable#14]
Наблюдаются проблемы со скачиванием PAC-скрипта из-за блокировки хостингом трафика со стороны РФ. На практике это как я понял обозначает частичное нарушение работы - из-за невозможности обновить PAC скрипт используемые сервера начали отваливаться, что влияет в первую очередь на трафик к самым популярным сайтам. У Обхода блокировок работа Антизапрета полностью остановилась, у Омеги частично.

Новички, можете скачать его вот здесь. Пока что без разницы откуда его скачивать ибо он давно не обновлялся. Но если у вас затруднён доступ к заблокированному сайту, переходите в режим TOR.
[antizapret.txt](https://github.com/user-attachments/files/18049639/antizapret.txt)

В инструкции по установке теперь тоже написано, что делать в подобном случае.

**Comment by Yastreb1333** [comment]
заработало
