### ISSUE TITLE
При попытке запуска AntiTor.exe завершается с ошибкой.

### ISSUE THREAD

**Issue by jackofallbrakes** [Verity-Freedom/Tor-Portable#15]
При попытке запуска AntiTor.exe завершается с ошибкой, лог прикреплен.
Конфигурационный файл не изменялся, кроме включения SafeLogging.

[info-notice.log](https://github.com/user-attachments/files/18052000/info-notice.log)
[torrc.txt](https://github.com/user-attachments/files/18052004/torrc.txt)

**Comment by Verity-Freedom** [comment]
> При попытке запуска AntiTor.exe завершается с ошибкой, лог прикреплен. Конфигурационный файл не изменялся, кроме включения SafeLogging.
> 
> [info-notice.log](https://github.com/user-attachments/files/18052000/info-notice.log) [torrc.txt](https://github.com/user-attachments/files/18052004/torrc.txt)

@jackofallbrakes выглядит как типичная ошибка седьмой винды. Я имею ввиду что на вин 7 была очень похожая ошибка и из-за неё и была создана версия для вин 7. У вас крашится не AntiTor, а lyrebird, это шифровальщик трафика, обеспечивающий устойчивое соединение, ответственный только за мосты, в логе это видно (Managed proxy "pluggable_transports\lyrebird" process terminated with status code 2). Для седьмой винды он или патчился (версия x64), или использовалась более старая версия (x86), ибо он написан на языке go, в котором из последних версий убрали обратную совместимость с win 7. Скорее всего вы случайно поставили не ту версию, ибо сейчас после сбоя Антизапрета идёт приток новых пользователей. Включение SafeLogging влияет только на то что он будет вырезать инфу из лога в редких случаях (в том числе из лога командной строки, который видите только вы, потому изначально и не было смысла оставлять его включённым), он был выключен ещё человеком, у которого я брал и потом полностью переписал этот файл конфигурации, ошибка не из-за этого.

**Comment by Verity-Freedom** [comment]
@jackofallbrakes в логе также написано что программа запущена на windows 8. Возможно если у вас непосредственно windows 8 то будет та же самая ошибка что и на win 7, ибо у win 8 поддержка тоже давно прекращена. Я достоверно знаю только о запуске без ошибок на win 10 и win 11, а про win 8 написал превентивно предполагая, что будет работать. Если у вас win 8 или win 8.1 дайте знать. Тогда будет исправлено описание файлов. Пробуйте версии для win 7 x64 и win 7 x86.

**Comment by jackofallbrakes** [comment]
@Verity-Freedom в том и дело что ОС - обычная Windows 10, версия 10.0.19045.5131. Режим совместимости отключен.
lyrebird от 14.11.2024, скачан в архиве последнего релиза.

при прямом запуске lyrebird ругается на отсутсвие библиотеки:
fatal error: acryptprimitives.dll not found                                                                                                                                                                        

![explorer_okKvteeaiH](https://github.com/user-attachments/assets/52f1beb2-c6a5-430a-86b9-c513e6631174)
![explorer_iYkJHmtkx3](https://github.com/user-attachments/assets/e32bf396-d3ef-422f-bc7a-5023c68a6e01)

**Comment by Verity-Freedom** [comment]
> @Verity-Freedom в том и дело что ОС - обычная Windows 10, версия 10.0.19045.5131. Режим совместимости отключен. lyrebird от 14.11.2024, скачан в архиве последнего релиза.
> 
> при прямом запуске lyrebird ругается на отсутсвие библиотеки: fatal error: acryptprimitives.dll not found
> 
> ![explorer_okKvteeaiH](https://private-user-images.githubusercontent.com/56634763/393620869-52f1beb2-c6a5-430a-86b9-c513e6631174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NzkzOTcsIm5iZiI6MTczMzY3OTA5NywicGF0aCI6Ii81NjYzNDc2My8zOTM2MjA4NjktNTJmMWJlYjItYzZhNS00MzBhLTg2YjktYzUxM2U2NjMxMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE3MzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3OGU0OGJiYzdmMWYyZWJiMGQ3M2NjMDA4ODUxOTJiMGI2Y2Y1NWViZWViODU3NWU0MGNmZTBmN2U4Y2U2NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WpzzlpP0NB1uFbWwF9mifbMW4qZ3rz7Vic2iuKguUbI) ![explorer_iYkJHmtkx3](https://private-user-images.githubusercontent.com/56634763/393621791-e32bf396-d3ef-422f-bc7a-5023c68a6e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NzkzOTcsIm5iZiI6MTczMzY3OTA5NywicGF0aCI6Ii81NjYzNDc2My8zOTM2MjE3OTEtZTMyYmYzOTYtZDNlZi00MjJmLWJjN2EtNTAyM2M2OGE2ZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE3MzEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOTAzMzIwZTNjNWVlN2EwZmZhMjQ4NThmMjUzMmY2YjAyM2NlOWZkZjQ3OWI5ZTI4OWY0NDUxOGViNzYxZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m36uFTvIukZcQOKSjTvLgEpQx9zVouwAY8EJmatwc6k)

У меня на вин 10 оно замечательно работало и у многих других оно замечательно работает. Сейчас с ноутбука на вин 11 сижу у которого примерно то же ядро что и у вин 10. Вы единственный у кого lyrebird на вин 10 крашится с такой ошибкой. Других жалоб не было на подобное. Возможно у вас пиратская винда с вырезанными обновлениями. Я ничего не чищу можете полазить по Новости и фидбэк или по закрытым issues, не было ни у кого такой ошибки, притом что уже 115 звёзд, программа довольно популярна. Недавно был довольно большой апдейт кода но lyrebird в нём я совсем не трогал. У меня при отдельном запуске Lyrebird просто сразу закрывается и об ошибках не сообщает. И как я понял вы сразу win 8+ ставили, потому что например версия win 7 x64 на 10 винде не пойдёт из-за несовместимости применённого патча. Версию Win 7 x86 ставьте тамошний lyrebird пашет даже на собственно win 7 x86, а функционально хуже не должно быть, тот же протокол он поддерживает. Но если не поможет вам надо переустанавливать винду. Она сломана. Всегда ставьте винду через media creation tool, как минимум профессиональную редакцию, и активируйте ключом.

**Comment by Verity-Freedom** [comment]
@jackofallbrakes ваша ошибка имеет прямое отношение к патчу который я применял для win 7 в версии win 7 x64. То есть вы ИЛИ по ошибке поставили версию для вин 7, или вашей системе наоборот нужна версия для вин 7 из-за того что она пиратская/модифицирована тем или иным образом. Пробуйте по одному все три версии, вин 7 x64, вин 7 x86, вин 8+. Если не пойдёт ни одна, сносите винду. Версия Вин 7 x86 работает одинаково на всех виндах с 7 по 11 в любых редакциях.
![image](https://github.com/user-attachments/assets/b7e527f7-4ccd-4974-b066-37afb1189561)

**Comment by Verity-Freedom** [comment]
> @Verity-Freedom в том и дело что ОС - обычная Windows 10, версия 10.0.19045.5131. Режим совместимости отключен. lyrebird от 14.11.2024, скачан в архиве последнего релиза.
> 
> при прямом запуске lyrebird ругается на отсутсвие библиотеки: fatal error: acryptprimitives.dll not found
> 
> ![explorer_okKvteeaiH](https://private-user-images.githubusercontent.com/56634763/393620869-52f1beb2-c6a5-430a-86b9-c513e6631174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODA3NzgsIm5iZiI6MTczMzY4MDQ3OCwicGF0aCI6Ii81NjYzNDc2My8zOTM2MjA4NjktNTJmMWJlYjItYzZhNS00MzBhLTg2YjktYzUxM2U2NjMxMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE3NTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhZTdhNmJmOTkyNDM2NWViMDExYzRjNDViYTM4N2JkYWQ5ZWZhOGU5OTNkMDM4ZDY4ZmU4NDYyYmJlMmRjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FAXciUBs6CbuEIbk_iKSNJCYY8y8-fpdU1LkQCxIk68) ![explorer_iYkJHmtkx3](https://private-user-images.githubusercontent.com/56634763/393621791-e32bf396-d3ef-422f-bc7a-5023c68a6e01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2ODA3NzgsIm5iZiI6MTczMzY4MDQ3OCwicGF0aCI6Ii81NjYzNDc2My8zOTM2MjE3OTEtZTMyYmYzOTYtZDNlZi00MjJmLWJjN2EtNTAyM2M2OGE2ZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDE3NTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMDlmZWJkOTQ1NWQ2NjY3M2VhNjlhMGVkNjJmZTdjZGI3OWNjNTExN2IzYWQxMjViNDdhMDAxMzc1ZDhkZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CJQ-sRpTZc-S7Xx23kr8gqY21zgZxTP_9_RZYOiUwWA)

@jackofallbrakes у вас lyrebird из версии для win 7 x64, вы по ошибке поставили не ту версию, у оригинального дата изменения в нулевом году, а не 14 ноября 2024. И файл FIX ZAPRET WIN 7 есть только в версиях для Win 7.
![image](https://github.com/user-attachments/assets/f13601df-f0e6-432b-a61d-4d1d6e708a9a)
![image](https://github.com/user-attachments/assets/c225a3fc-9532-484c-b953-8e5b87f62cc2)

**Comment by Verity-Freedom** [comment]
@jackofallbrakes я сразу написал что именно произошло в вашем случае, могли бы уже догадаться исправить проблему сами.
![image](https://github.com/user-attachments/assets/e1ad24c3-ebcd-45c4-b77c-cc0c35493f89)

**Comment by jackofallbrakes** [comment]
Все, понял. Мой косяк, прошу прощения за ложную тревогу.
