### ISSUE TITLE
Проблема с установкой Тор

### ISSUE THREAD

**Issue by 28dlater** [Verity-Freedom/Tor-Portable#3]
Не силен в подобном, по совету скачал архив с антитор, распаковал, что делать дальше не понимаю, пробовал запустить через ехе файл AntiTor, как программу. пишет вот это , ( tor.exe не является приложение Win32) .Видимо я что то делаю не так, прошу прощения, я простой юзер, далекий от технологий.

**Comment by Verity-Freedom** [comment]
> tor.exe не является приложение Win32

Я тоже не понимаю пока что. Вы первый у кого такая ошибка. У вас какая версия Windows?

Если скачивали 5 часов назад или больше - можете смело перекачивать, за это время обновилась версия. А во-вторых такой ошибки я ещё не встречал. Она не массовая.

**Comment by 28dlater** [comment]
Скачивал не год назад, мне дали ссылку на новую актуальную версию. Система хр....

**Comment by 28dlater** [comment]
20 сентября мне скинули ссылку, в этот же день и скачал, последную версию программы, как понимаю.

**Comment by Verity-Freedom** [comment]
> Система хр

Ну это полагаю всё объясняет.

Я рекомендую вам хотя бы семёрку. Она ничем не хуже чем xp. Я люблю десятку, я люблю семёрку, xp очень устарел уже, там трудно с ним.

Там есть установка службой и установка экзешником. Рекомендую ещё пройти вниз по адресу AntiTor\tor\tor.exe, попробовать запустить его и посмотреть, что пишет.

**Comment by 28dlater** [comment]
Это в общем понятно, но у меня дело не в любви к хр =) а в том, что нужно скачать тот же винду 7 с того же торрента, а он блокирован, но это пол дела, нужно установить винду, а мои познания в этом равны нулю по сути. Прошу прощения, за тупость, вам то все понятно, что сие означает ? 
(Там есть установка службой и запуск экзешником. Рекомендую ещё пройти вниз по адресу AntiTor\tor\tor.exe, попробовать запустить его и посмотреть, что пишет.) я не тупой, самый обычный пользователь, далекий от этого всего, как волочкова от балета )

**Comment by 28dlater** [comment]
Вот что у меня в папке, пробовал запустить ехе , пишет что не является приложением win32,..... Что делать совсем не понятно, говорю же, я лох в этих технологиях =)
data\
tor\
runet-censorship-bypass-0.0.1.63-full-rc0.crx
AntiTor.exe
readme-youtube.txt
readme.txt
torrc.txt
runet-censorship-bypass-0.0.1.64-full-rc0.xpi

**Comment by Verity-Freedom** [comment]
> Что делать совсем не понятно

Проще всего было бы обновить винду. Но можете попробовать открыть папку tor, запустить там tor.exe и посмотреть, что произойдёт в этом случае.

**Comment by d1mulka** [comment]
У меня на запускаеться новая версия

**Comment by d1mulka** [comment]
В этом antitor-service пишет что служба не установлена

**Comment by d1mulka** [comment]
нашёл как решить проблему из новой папки torrc перенести в старую у меня заработал

**Comment by 28dlater** [comment]
Проще всего было бы обновить винду. Но можете попробовать открыть папку tor, запустить там tor.exe и посмотреть, что произойдёт в этом случае.

Ну не так и просто, когда лет цать пользуется хр, то ставить новую, в которй ничего не знаешь, не так и просто,особенно когда последний раз ставил старую винду лет 10 назад и мало что понимаешь в компах.... ( Открыл папку тор, запустил тор.ехе, написали просто и лаконично, программа не запускается...

**Comment by Verity-Freedom** [comment]
> программа не запускается

Тогда тут всё.

Ставьте десятку или семёрку.

**Comment by Jinie22** [comment]
После запуска (от админа) файла antitor.exe или cmd, ничего не происходит и никакие службы не добавляются. Windows 11 23H2

**Comment by Verity-Freedom** [comment]
> После запуска (от админа) файла antitor.exe или cmd

Вам нужно качать архив в релизе, а не отдельные файлы в исходном коде (main), иначе ничего не произойдёт. Они не добавляют службы, они открывают программу, работающую на фоне. Antitor.cmd есть только в исходном коде. Притом, если вы уже добавили службу от админа при помощи antitor-service.cmd, вам нужно или пользоваться этой службой, или удалить её. Пока служба действует, программа запускаться не будет. Программа всегда запускается в свёрнутом виде.

**Comment by Verity-Freedom** [comment]
> Возможно, я делаю что-то не так, если она у меня не работает в папке



> > После запуска (от админа) файла antitor.exe или cmd, ничего не происходит и никакие службы не добавляются. Windows 11 23H2
> 
> Возможно кому-то поможет, но у меня не запускалась прога, пока не перенес папку с программой в корень диска "С, D и тд.".
> 
> p/s Если лежит в какой-то папке - не запускается. Возможно, я делаю что-то не так, если она у меня не работает в папке. antitor-service.cmd - не запускал.

Возможно у вас стоит старая версия, там были проблемы с этим примерно неделю назад в процессе перехода с версии 1.2 на 1.3. У меня воспроизвести ошибку не получается, т. к. программа настроена автоматически подстраивать пути для себя (собственно это и было сделано при смене версии, дабы получить совместимость со службой). Может Майкрософты что-то сделали в своей 11-й винде, что такой простой софт перестал корректно работать.

**Comment by Bu11d03er** [comment]
> Возможно у вас стоит старая версия
Я сегодня впервые узнал о вашем софте и скачал его последнюю версию 1.3
Если попытаться запустить из папки, оно на миг появляется в панели задач в виде открывшегося окна и сразу исчезает. Возможно, программа где-то ведет логи, чтобы посмотреть в чем проблема? готов их предоставить, чтобы улучшить софт.

**Comment by Verity-Freedom** [comment]
> Если попытаться запустить из папки, оно на миг появляется в панели задач в виде открывшегося окна и сразу исчезает

У меня и у многих других оно и на рабочем столе, и на диске C, и на диске D открывается. У вас надеюсь официальная лицензионная Windows 11, а не сборка чья-то.

Ну то есть я без понятия, в чём проблема может быть. Возможно почему-то у вас оно не успевает заменить пути до того как запустится, там может стоит какие-то паузы добавить. Но вы буквально первый, у кого такая проблема есть.

**Comment by Verity-Freedom** [comment]
> Программа где-то ведет логи, чтобы посмотреть в чем проблема

Первыми строчками файла torrc.txt указываются пути. При запуске antitor.exe должна происходить их замена в автоматическом режиме. Попереносите из директории в директорию папку, пробуйте запустить antitor.exe и смотрите, меняется ли что-то в torrc.

У win 11 имеется привычка запихивать всё подряд в onedrive, возможно дело в этом, возможно у вас чья-то плохая сборка, возможно вы архив не распаковали (его надо распаковать).

**Comment by Verity-Freedom** [comment]
Возможно получилось воспроизвести проблему. С русскими символами программа дружит плохо, не смогла путь заменить в директории, имеющей русское название. Будем смотреть.

**Comment by Verity-Freedom** [comment]
@Bu11d03er @Jinie22 

Выявлен баг: несовместимость с русскими символами в директории.

То есть если оно будет условно находиться по адресу C:\Крутые программы\AntiTor, то работать не будет. В файле torrc.txt вместо корректного обозначения директории появляются знаки вопроса. Возможно придумаем, что с этим делать, но пока так.

**Comment by Bu11d03er** [comment]
Вопросики в файле видел сразу, т.к начал искать сразу логгирование проблемы в разных файлах, но проблема как я понимаю не только в них. После того как она не запустилась в папке, где были русские буквы, я перенес программу в "C:\Program Files\AntiTor". Там она у меня тоже не запустилась. Потом вынес в корень диска, и там запустилась.

Сейчас проверил, по пути "C:\Program Files\AntiTor" - она начала работать. Странно. Ну допустим, это глюк какой-то был в системе или в моей голове. Ладно, будем держать её пока, не в папках с кириллицей.

**Comment by Verity-Freedom** [comment]
> C:\Program Files\AntiTor

Program Files это админская директория, там может требовать права администратора.

Я баг этот исправил у себя, скоро выйдет версия 1.35, перекачаете.

**Comment by Verity-Freedom** [comment]
@DesuIsALie твой скрипт всё равно проблемный оказался по итогу, но я починил его там, скоро выйдет новая версия. Всё равно огромное спасибо за помощь.

**Comment by Verity-Freedom** [comment]
@Bu11d03er @Jinie22

Баг исправлен, скачайте новый релиз.
https://github.com/Verity-Freedom/Tor-Portable/releases/tag/v1.3.5

**Comment by Verity-Freedom** [comment]
Проблема решена.
