### ISSUE TITLE
Youtube и Discord

### ISSUE THREAD

**Issue by alan-zxs** [Verity-Freedom/Tor-Portable#6]
Всё работает, кроме ютуба. Свежая сборка, выставлял антизапрет/антицензорити, применил все настройки, менял мосты.
![1](https://github.com/user-attachments/assets/516daa76-fc88-4074-bf80-087c7d928e55)
![2](https://github.com/user-attachments/assets/4dde7c38-1df9-462b-9ce9-4d94cb76f5ba)
![3](https://github.com/user-attachments/assets/1134d82e-fa30-4f3c-a3d7-c9b940ab9145)
[logs.txt](https://github.com/user-attachments/files/17116016/logs.txt)
[torrc.txt](https://github.com/user-attachments/files/17115995/torrc.txt)

**Comment by Verity-Freedom** [comment]
> Всё работает, кроме ютуба

Ютуб замечательно работает. Не хуже, чем вчера или позавчера. Проходит все мои традиционные тесты. Под Ютуб специально всё и оптимизировалось.

Прямо в тот момент когда вы написали (ну примерно) вышла новая версия 1.35 с исправлением багов. Если не качали, скачайте.

С флагами у вас всё в порядке.

В расширении обход блокировок необходимо поставить в исключения (проксировать - да) адреса:

*.youtube.com
*.youtu.be
*.ytimg.com
*.googlevideo.com
*.googleapis.com
*.googleusercontent.com
*.gstatic.com
*.ggpht.com

Вот эти 8 первостепенны, остальные я не видел, чтобы хоть на что-то влияли.

Если не поможет убирайте из конфига torrc.txt строчку:

ExitNodes 45.95.169.223/26

Но это прям крайняя мера ибо она нужна и приносит гораздо больше пользы чем потенциально вреда.

**Comment by Verity-Freedom** [comment]
> менял мосты

С мостами текущими всё в порядке, все 4 работают.

**Comment by Verity-Freedom** [comment]
У вас два лишних моста используются вот тут. Уберите их, скорее всего в них проблема. Они устаревшие и у меня используются только как резервные (обозначены символом "#" и программа их не видит), их состояние я не проверяю.
![image](https://github.com/user-attachments/assets/be04223f-1a0e-472c-899e-419fae8e97d0)

**Comment by Verity-Freedom** [comment]
@alan-zxs видите, у вас в логах ошибку дают два лишних моста, которые вы добавили. Тут несложно сложить 2+2.
![image](https://github.com/user-attachments/assets/dfa5cb40-7c33-4f35-aba8-f01f5f3a1634)
![image](https://github.com/user-attachments/assets/c38b7e3b-c09b-4bc6-8328-b542c2cd2c1d)

**Comment by Verity-Freedom** [comment]
Также хочется отметить, что антизапрет судя по всему опять лежит, использование режима антицензорити будет более предпочтительным.

**Comment by cornkid** [comment]
Здравствуйте, я не поняла как создать отдельную ветку, поэтому пишу здесь, у меня гудбай дпай работает, дискорд грузит, но я могу только текстом общаться, а в голосовые каналы/звонки заходить не могу

**Comment by cornkid** [comment]
можете пожалуйста помочь? или помочь с оплатой prostovpn?

**Comment by Verity-Freedom** [comment]
> Здравствуйте, я не поняла как создать отдельную ветку, поэтому пишу здесь, у меня гудбай дпай работает, дискорд грузит, но я могу только текстом общаться, а в голосовые каналы/звонки заходить не могу

Вам не ко мне к сожалению. Вопросы про Goodbyedpi задавайте разработчикам Goodbyedpi. Здесь совсем другие средства используются. Совместно использовать расширение Обход блокировок и Гудбай я не рекомендую. Могу только посоветовать выключить Goodbyedpi и использовать мой портативный Тор совместно с расширением Обход блокировок рунета.

**Comment by Verity-Freedom** [comment]
> если я выключу гудбай то дискорд не работает, вы можете у себя проверить, работает ли дискорд без впн?

Особенность Гудбая в том что он искажает интернет-подключение так, что получается обходить блокировки, наложенные властями РФ, включая например замедления Ютуба всякие (кстати скажу крамольную вещь, но в случае Ютуба замедление сравнительно по делу, Ютуб не очень хорошо относится к своим российским пользователям и имеет сомнительную политику модерации, к тому же замедление по итогу позволило популяризовать средства обхода блокировок, и это гораздо лучше, чем если бы Ютуб просто заблокировали).

Но Гудбай сам по себе - это с одной стороны сложная программа, а с другой он не меняет ip-адрес, поэтому не сможет прорвать блокировку на стороне, если кто-либо видит, что вы русский. В случае с Ютубом это особенно актуально, ибо он активно использует крайне антиморальные блокировки по авторским правам только для россиян, для меня подобное - однозначная дискриминация по национальному признаку. Поэтому опять же, даже не могу однозначно осуждать власти РФ за санкции по отношению к Ютубу (просто важно понимать, что замедление - от властей РФ, а не от Ютуба).

Так вот, Гудбай, если вы им пользуетесь, фундаментально не может прорывать некоторые блокировки (в то время как мой портативный Тор обходит почти любые, совместно с работающим антизапретом - вообще любые). При этом Гудбай работает крайне нестабильно без всяких гарантий, буквально на честном слове, и сам по себе может сломать некоторые сайты. Но Гудбай - очень сложное шаманство, и идеологически мне он нравится, хотя не совсем приятно, что он стал популярнее всего на свете и пиарился везде подряд, ибо является слишком сложной и уязвимой программой, в результате люди каждый день жалуются на то, что он работает неидеально. Я допускаю, что Гудбай в вашем случае может ломать Дискорд. Лично у меня Дискорд запускается без всяких VPN. Я это только что проверил, но возможно ваш провайдер чудит, поэтому то что у вас Дискорд в принципе без Гудбая не открывается тоже возможно.

Я вам посоветую:

1) Скачать графическую версию Goodbye dpi. Именно графическую версию я всем качать и рекомендую. Она регулярно обновляется и использовать её проще чем обычную консольную версию. Вы можете сделать это здесь https://topersoft.com/programs/launchergdpi. Там у вас будут на руках всевозможные настройки. Наиболее важной из них является использование Гудбая по отношению ко всем сайтам или только по отношению к домёнам из списка. А Дискорда ни в каком списке нет, просто у вас чудит провайдер. Но если у вас Дискорд уже изменялся Гудбаем, и не работали голосовые звонки, а без Гудбая Дискорд вообще не работал, то это не поможет.

2) Все ваши vpn должны быть выключены. Вы не должны использовать малосовместимые способы обхода совместно. Гудбай в принципе мало с чем совместим, ибо использует кардинально другие технологии. Например мой портативный Тор и расширение Обход блокировок рунета совместимы просто превосходным образом, с Гудбаем там совместимости не будет.

3) Попробуйте использовать Дискорд онлайн, совместно с портативным Тором или сам по себе. Заходите на discord.com и пробуйте войти в свой аккаунт. Если не получается - нажимайте "проксировать - да" в расширении Обход блокировок рунета при запущенном портативном Торе, и Дискорд будет проксироваться им.

4) Если всё это не помогло, можете использовать мой портативный Тор в качестве отдельного VPN, проксирующего весь трафик, а не совместно с расширением (хотя у такого подхода и будут определённые минусы, например совместно с расширением его уже использовать не получится, поэтому не все блокировки сможете обойти). Для этого в параметрах прокси сервера Виндоус пишите "использовать прокси-сервер", адрес 127.0.0.1, порт - 9050.

Как-то так, дальше сами.

**Comment by cornkid** [comment]
а через какой сервер у вас ваш прокси? и можно ли как-то с вами связаться, чтобы не публично скриншоты и тд скидывать, а-то боюсь

**Comment by Verity-Freedom** [comment]
> а через какой сервер у вас ваш прокси

Это локалхост, он у всех одинаковый, можно сказать, что он открывается на самом компьютере, и связывается с серверами Тора на стороне. Можете прямо здесь скидывать. Мне много где лучше свои почты следить не стоит. Ибо уже меня могут отследить и начать задавать мне вопросы в наиболее тяжёлом случае. Хотя пока что то что я сделал не является незаконным.

**Comment by Verity-Freedom** [comment]
> много кто, очень много кто жалуется на дискорд

Так наши доблестные цензоры работают, это правда, но центральной блокировки не было. Может у Дискорда свои какие-то проблемы тоже есть.

**Comment by Verity-Freedom** [comment]
@cornkid на профильном сайте по борьбе с цензурой рекомендуют ставить адреса:

discord.com
gateway.discord.gg
cdn.discordapp.com
discordapp.net

В исключения, будь то портативный Тор или goodbye dpi.

**Comment by Verity-Freedom** [comment]
@cornkid ещё сказали, что Гудбай дпи здесь вряд ли поможет полностью, особенно для голоса.
![image](https://github.com/user-attachments/assets/ec0478e9-882d-46e9-afca-b75a535cc4ed)

**Comment by cornkid** [comment]
Здравствуйте, вариант с прокси через ваш сервер ещё в силе?

**Comment by cornkid** [comment]
я попробовала ваш прокси, он не работает

**Comment by Verity-Freedom** [comment]
> Здравствуйте, вариант с прокси через ваш сервер ещё в силе?

@cornkid за это время выяснилось что Тор сам по себе как прокси не работает. Для его использования на системный трафик (собственно Дискорд) нужно использовать или расширение SwitchyOmega (браузерный трафик; сам начал использовать его таким образом) или взломанный Proxifier (весь трафик вообще; он очень быстро ломается при таком использовании, никому не рекомендую). К тому же вероятно не будет работать войс как я слышал, ибо у Тора та же несовместимость с UDP, что и у Goodbye dpi. Для ваших целей я рекомендую скачать Psiphon TM, он идеально для этого подходит. Минусы - он значительно медленнее Тора, но имеет очень высокую степень противодействия цензуре, сайты на стороне его не блокируют и для Дискорда его скорее всего хватит. Goodbye dpi и расширение Обход блокировок рунета должны быть выключены.
https://github.com/Verity-Freedom/Tor-Portable/releases/tag/v1.0

**Comment by cornkid** [comment]
а он сильно на пк влияет?

**Comment by cornkid** [comment]
в плане, производимость

**Comment by cornkid** [comment]
скачала, запустила runme, запускается на секунду и выключается

**Comment by Verity-Freedom** [comment]
> в плане, производимость

Никак не влияет. Должен постоянно работать на фоне просто.

**Comment by Verity-Freedom** [comment]
> запускается на секунду и выключается

Значит что-то не так сделали. Я же объяснил все остальные vpn должны быть выключены.

**Comment by cornkid** [comment]
они выключены

**Comment by Verity-Freedom** [comment]
@cornkid я обновил релиз убрав из него папку, которую Psiphon создаёт при первичном подключении. Подумал что у вас могла быть в этом проблема.

**Comment by Verity-Freedom** [comment]
> но в звонки в дискорде также не могу подключиться

Через Psiphon не можете? Я тут уже ничем не смогу помочь.

**Comment by cornkid** [comment]
да, черещ псифон не могу

**Comment by Verity-Freedom** [comment]
> да, черещ псифон не могу

А в целом-то обход блокировок работает у вас? Вы проверили?

Надо попробовать у себя посмотреть конечно.

**Comment by cornkid** [comment]
обход-то работает, только мне звонки нужны :(

**Comment by Verity-Freedom** [comment]
@cornkid зафиксировал проблему. У меня тоже звонки не работают, притом что сам Дискорд работает даже без VPN. Тут только AmneziaWG поможет. Там большинство VPN платные, но я знаю один бесплатный, к сожалению с ограничением по трафику.
https://github.com/amnezia-vpn/amneziawg-windows-client/releases/tag/1.0.0

К нему добавляйте файл конфигурации:
https://disk.yandex.ru/d/k9DXAaIDPFeTmA

Это вернёт звонки. Но есть достаточно суровое ограничение - всего 100 мегабайт в день. Долго им пользоваться не получится. Если нужно убрать ограничение - платите им денежку.
https://frkn.org/ru

**Comment by Verity-Freedom** [comment]
Для голоса в Дискорде устанавливайте Planet, реально единственный выход без ограничений трафика сейчас. Лично мне здесь нечего предложить, кроме стороннего решения.

Чтобы его скачать вам тоже ВПН нужен если что.
https://freevpnplanet.com/download/

@cornkid вот решение проблемы для тебя.

**Comment by Verity-Freedom** [comment]
Пусть останется пока открытым.

**Comment by cornkid** [comment]
а дс с планет впном работает?

**Comment by Verity-Freedom** [comment]
> а дс с планет впном работает?

Я только что проверил что это единственный широко известный бесплатный VPN без ограничений трафика который даст голос в Дискорде. Все остальные так не умеют.

**Comment by cornkid** [comment]
спасибо

**Comment by Verity-Freedom** [comment]
@cornkid

На NTC дали бесплатный генератор конфигов для AmneziaWG.

Делаем всё по здешнему гайду
https://github.com/ImMALWARE/bash-warp-generator
https://github.com/amnezia-vpn/amneziawg-windows-client/releases/tag/1.0.0

Потенциально значительно удобнее чем планет ибо программа полностью бесплатная и опенсорсная.

**Comment by cornkid** [comment]
спасибо огромное
