### ISSUE TITLE
WIndows Defender видит троян в приложении и не дает установить его

### ISSUE THREAD

**Issue by 69gamerxd** [Verity-Freedom/Tor-Portable#7]
![image](https://github.com/user-attachments/assets/765e7c52-8ef0-46d4-b999-5a7dbc99f503)
Скачать файл невозможно без отключения защиты в реальном времени

**Comment by Verity-Freedom** [comment]
> ![image](https://private-user-images.githubusercontent.com/182085727/370743064-765e7c52-8ef0-46d4-b999-5a7dbc99f503.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzUyMTUsIm5iZiI6MTcyNzI3NDkxNSwicGF0aCI6Ii8xODIwODU3MjcvMzcwNzQzMDY0LTc2NWU3YzUyLThlZjAtNDZkNC1iOTk5LTVhN2RiYzk5ZjUwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxNDM1MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDEzOWM0NjU1MzA1YWI1MDUyNmI0Zjg5Y2MzN2U0OWY0NzExNjNjMDg4MTRiYjdmZjVmNmY2Yjg1ZDA1YWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zTJARAk7yaFAPCy6CPEgigBohS7rRxR8zTddwKbeVYs) Скачать файл невозможно без отключения защиты в реальном времени

Известный фолспозитив, windows defender и на любые кряги ругается, если скачивать их.
![image](https://github.com/user-attachments/assets/56fdf2cd-9bb0-4fc0-8ebf-038809bb4d6d)

Об этом давно известно. См. https://github.com/Verity-Freedom/Tor-Portable/issues/1

По вирустоталу там не больше 20 из 70 антивирусов ругаются на антитор exe и не больше 10 из 60 на сам архив. Добавляйте файл или угрозу в исключения.

**Comment by Verity-Freedom** [comment]
У меня исключений для виндоус защитника очень много, потому что это невероятно агрессивный антивирус. Можете попробовать сменить на условного касперского.

**Comment by Verity-Freedom** [comment]
Тот же автор графической версии goodbye dpi тоже на windows защитника жалуется.
![image](https://github.com/user-attachments/assets/1ae30d7a-ab8b-42d6-89f5-06721a35c226)
