### ISSUE TITLE
Для восстановления голоса в Дискорде

### ISSUE THREAD

**Issue by Verity-Freedom** [Verity-Freedom/Tor-Portable#9]
Не буду себе причислять чужие заслуги. Тор так сделать не сможет. Качайте стороннюю программу.

На NTC дали бесплатный генератор конфигов для AmneziaWG.

Делаем всё по здешнему гайду
https://github.com/ImMALWARE/bash-warp-generator

Затем качаем программу и засовываем в неё получившийся файл.

https://github.com/amnezia-vpn/amneziawg-windows-client/releases/tag/1.0.0 (Amnezia WG, мало весит, быстрый автозапуск)
https://github.com/amnezia-vpn/amnezia-client/releases (Amnezia VPN, добавление программ в исключения чтобы избежать пинга и задержек)

Если не получилось сгенерировать, у меня в релизах уже есть конфиг с работающим на данный момент ключом.
https://github.com/Verity-Freedom/Tor-Portable/releases/tag/1.0

Кто думает, что портативный Тор больше не нужен - это не так. WARP в отличие от портативного Тора совершенно прозрачен и палит страну происхождения, НЕ справляясь с геоблокировками на стороне, а в Торе в теории страну можно даже выбрать точечно. Только портативный Тор даёт доступ к онионам (по понятным причинам). И то, и другое решение несовершенны, но очень хороши в своих сферах.

Буду очень рад, если поддержите финансово ImMALWARE, парень заслужил. Я лично отправил ему 1000 рублей через donation alerts только что, очень впечатлила проделанная работа.

Можно сделать это тут: https://www.donationalerts.com/r/notmalware

**Comment by KainXVIII** [comment]
У меня с антитором не открывается веб-дискорд..

**Comment by OjisanKG** [comment]
А за чей счет тут трафик прокачивается в итоге?

**Comment by Verity-Freedom** [comment]
> А за чей счет тут трафик прокачивается в итоге?

Ни за чей. Конечные сервера принадлежат Cloudflare WARP. То есть они как и Тор тоже никогда не исчерпаются.

**Comment by Verity-Freedom** [comment]
> У меня с антитором не открывается веб-дискорд, пофиг на голос..

Там SwitchyOmega нужен для подобного а не Обход, но голоса всё равно не будет, много смысла не вижу.

**Comment by KainXVIII** [comment]
> > У меня с антитором не открывается веб-дискорд, пофиг на голос..
> 
> Там SwitchyOmega нужен для подобного а не Обход, но голоса всё равно не будет, много смысла не вижу.

А как пользоваться? Мне голос и не нужен, только каналы.

**Comment by Verity-Freedom** [comment]
> > > У меня с антитором не открывается веб-дискорд, пофиг на голос..
> > 
> > 
> > Там SwitchyOmega нужен для подобного а не Обход, но голоса всё равно не будет, много смысла не вижу.
> 
> А как пользоваться? Мне голос и не нужен, только каналы.

Установить SwitchyOmega потом в настройках пошарманить.
![image](https://github.com/user-attachments/assets/0f74ef6f-09d0-40c7-8469-5ca58519023d)
![image](https://github.com/user-attachments/assets/d8515bdd-20a7-4043-becb-4143cbd60adf)
![image](https://github.com/user-attachments/assets/1ce9dfb9-8374-476e-9fb8-30ecc19357cb)
![image](https://github.com/user-attachments/assets/2eedebbb-bee0-4c57-acb6-ce686c55b22b)

**Comment by KainXVIII** [comment]
Спасибо, конечно, но это для меня слишком 😑

**Comment by cherryfan12** [comment]
> > Что теперь делать с дискордом? На мобилке работает с впн корректно; через веб морду без впн не работает вообще, с впн показывает главную страницу, но не открывает приложение. Анти тор не спасает отца русской демократии, как и Амнезия. В полном функционале удалось завести только через полноценный тор. Можно ли заставить работать приложение через расширение или антитор?
> 
> Можете ко мне в репозиторий обратиться я в этом плане всё подряд собираю. Но полноценно Тором Дискорд никак не вернуть, войса не будет. Только Амнезия.

Прикол в том, что у меня Амнезия (VPN Free) его не открывает. Антитор с дискордом тоже работать отказывается, только оригинальный тор запускает приложение.
Консоль https://shell.cloud.google.com/ из гайда, приложенного выше у меня висит часами и до конца не прогружается, соответственно, я не понимаю, откуда брать РАС скрипт и все прочие настройки. Только лишь скаченной Омеги недостаточно, чтобы шайтан машина заработала.

**Comment by cherryfan12** [comment]
Непонятно, почему дискорд не открывает встроенное приложение (через веб-интерфейс) при запущенном VPN. Главная страница работает, другие закрытые сайты тоже. А этот нет.

**Comment by Verity-Freedom** [comment]
> Антитор с дискордом тоже работать отказывается

@cherryfan12 потому что для такого нужно или switchyomega ставить чтобы входить в режим проксирования Тором всего браузерного трафика, или прописывать в Обходе планомерно все его адреса (а их довольно много), но войс это не вернёт. В Тор браузере СКОРЕЕ всего нет войса у Дискорда. Cloud shell запускать не надо ибо там скрипты рандомятся всего парой параметров - в результате почти идентичный скрипт работает много у кого, но пока работает, что конечно не очень хорошо с точки зрения безопасности. Лучше прешэреный скрипт скачать если не получается сгенерировать.

**Comment by Verity-Freedom** [comment]
> Спасибо, конечно, но это для меня слишком 😑

@KainXVIII для SwitchyOmega была создана более понятная визуальная инструкция. Объяснил как сумел.

**Comment by Eikinskjaldi89** [comment]
Дискорд [добавили](https://www.reddit.com/r/AmneziaVPN/comments/1g23y4j/the_entire_discord_is_now_accessible_via_the_free/) в Amnezia Free.

Сам таким вариантом Амнезии не пользовался, я так понимаю там через ВПН будут работать только адреса, добавленные разработчиками  (и это далеко не всё, что заблокировано в России), без возможности что-либо добавить/убрать. Но для Дискорда должно работать, а для остального есть Тор.

**Comment by Verity-Freedom** [comment]
Обновил readme.

**Comment by Verity-Freedom** [comment]
> без возможности что-либо добавить/убрать

Ну такая довольно жидкая тема конечно. Хотя amnezia VPN это российская компания.

**Comment by Verity-Freedom** [comment]
По моим впечатлениям и тестам варп/Амнезия чисто по цифрам быстрее чем Тор ну раз в 5-6 (15-20 mb/s против 90), но по факту она не слишком стабильно работает, в отличие от АнтиТора, а этих самых 15 mb/s как раз хватает на то, чтобы даже Ютуб в 2 К смотреть.

**Comment by Eikinskjaldi89** [comment]
> По моим впечатлениям и тестам варп/Амнезия чисто по цифрам быстрее чем Тор ну раз в 5-6 (15-20 mb/s против 90), но по факту она не слишком стабильно работает

Ну у меня с Амнезией свой сервер в Исландии. Скорость-то прекрасная (180+ MB/s на AmneziaWG, 150+ на Xray), но раздельное туннелирование на ПК работает очень криво (при том, что на Андроиде всё отлично). Можно конфиг Xray импортировать в клиент, умеющий работать как прокси (аналогично Тору), но тогда опять же не будет голоса в Дискорде. В общем даже с собственным сервером одного решения для всего не получается.

**Comment by Verity-Freedom** [comment]
@Eikinskjaldi89 в Amnezia VPN по сравнению с amnezia WG есть раздельное туннелирование. Хорошо что Xray и Amnezia WG такую высокую скорость поддерживают. У меня у домашнего интернета скорость ниже.

**Comment by Eikinskjaldi89** [comment]
> Amnezia VPN по сравнению с amnezia WG есть раздельное туннелирование, хотя может и неидеальное.

Я про него и пишу. Уж слишком оно неидеальное.

**Comment by Verity-Freedom** [comment]
Надо бы уже менять тариф хотя бы на 500 мегабит...

**Comment by Verity-Freedom** [comment]
Занимался помощью одному человеку с портированием на MacOs, в процессе убрал из релиза лишний код.
